# Generated by Django 5.2.6 on 2025-09-11 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="user.doctor",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="user.patient",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="head_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.doctor",
            ),
        ),
        migrations.AddField(
            model_name="doctorschedule",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="user.doctor",
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="appointment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_record",
                to="bookings.appointment",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="appointment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="bookings.appointment",
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookings.appointment",
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_slots",
                to="user.doctor",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("doctor", "appointment_date", "appointment_time")},
        ),
        migrations.AlterUniqueTogether(
            name="doctorschedule",
            unique_together={("doctor", "day_of_week", "start_time")},
        ),
        migrations.AlterUniqueTogether(
            name="timeslot",
            unique_together={("doctor", "date", "start_time")},
        ),
    ]
